import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import RegisterModal from "@/components/modals/RegisterModal";
import LoginModal from "@/components/modals/LoginModal";
import { getCurrentUser } from "./data-query/getCurrentUser";
import RentModal from "@/components/modals/RentModal";
import ImageUpload from "@/components/image-upload";
import ImageUploadModal from "@/components/modals/ImageUploadModal";
import ToasterProvider from "@/providers/ToasterProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser()
  return (
    <html lang="en">
     
      <body className={inter.className}>

        <Navbar currentUser={currentUser}/>
        <RegisterModal/>
        <LoginModal/>
        <ToasterProvider/> 
        <ImageUploadModal/>
        <RentModal/>
        <div className="pb-20 pt-28">
        {children}
        </div>
        </body>
    </html>
  );
}
